kind: pipeline
type: exec
name: arm64

platform:
  os: linux
  arch: arm64

clone:
  disable: false

trigger:
  branch:
    - yoe/mut
  event:
    - push
    - pull_request

steps:
  - name: build
    commands:
      - git clone --recurse-submodules -j8 -b master git://github.com/YoeDistro/yoe-distro.git yoe
      - cd yoe
      - git checkout master
      - git pull
      - git submodule update --recursive --init
      - rm -rf sources/meta-openembedded
      - ln -sf `pwd`/../ sources/meta-openembedded
      - export DOCKER_REPO=none
      - export LANG=en_US.UTF-8
      - export SSTATE_CACHE_DIR=/scratch/sstate-cache
      - echo "Started build# $DRONE_BUILD_NUMBER"
      - echo "sstate cache dir = $SSTATE_CACHE_DIR"
      - echo "building $DRONE_GIT_HTTP_URL, branch $DRONE_SOURCE_BRANCH"
      - echo export DOCKER_REPO=none > local.sh
      - echo export LANG=en_US.UTF-8 >> local.sh
      - echo export SSTATE_CACHE_DIR=/scratch/sstate-cache >> local.sh
      - cp conf/local.conf.sample conf/local.conf
      - echo SSTATE_DIR = \"$SSTATE_CACHE_DIR\" >> conf/local.conf
      - echo IMAGE_CLASSES += \"testimage testsdk\" >> conf/local.conf
      - echo INHERIT += \"report-error rm_work\" >> conf/local.conf
      - echo ERR_REPORT_SERVER = \"errors.yoctoproject.org\" >> conf/local.conf
      - echo ERR_REPORT_PORT = \"80\" >> conf/local.conf
      - echo ERR_REPORT_USERNAME = \"Drone Autobuilder\" >> conf/local.conf
      - echo ERR_REPORT_EMAIL = \"info@yoedistro.org\" >> conf/local.conf
      - echo TOOLCHAIN = \"clang\" >> conf/local.conf
      - /bin/bash -c "sed -i -e 's/PACKAGE_FEED_URI.*$//' conf/site.conf"
      - /bin/bash -c "sed -i -e 's/SDK_UPDATE_URL.*$//' conf/site.conf"
      - /bin/bash -c ". ./qemuarm64-envsetup.sh && bitbake yoe-qt5-image"
      - echo TESTIMAGE_AUTO_qemuall = \"1\" >> conf/local.conf
      - /bin/bash -c ". ./qemuarm64-envsetup.sh && bitbake yoe-sdk-image"
      - /bin/bash -c ". ./qemuarm64-envsetup.sh && resulttool report build/tmp/log/oeqa"
      - /bin/bash -c ". ./qemuarm64-envsetup.sh && ./sources/openembedded-core/scripts/sstate-cache-management.sh -d -y"
---
kind: pipeline
type: exec
name: cleanup

platform:
  os: linux
  arch: arm64

clone:
  disable: true

trigger:
  branch:
    - master
  event:
    - push
    - pull_request
  status:
    - success
    - failure

steps:
- name: clean
  commands:
    - echo "Deleting tmpdir for build# $DRONE_BUILD_NUMBER"
    - rm -rf /scratch/tmp-clang-$DRONE_BUILD_NUMBER

depends_on:
- arm64
